include:
  - https://cnb.cool/zls-tools/vm/-/blob/main/ide.yml
  - https://cnb.cool/zls-tools/vm/-/blob/main/tools/sync-github-sohaha.yml
  - https://cnb.cool/zls-tools/vm/-/blob/main/tools/install-tools.yml